language: node_js
node_js: node

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages

install:
  - npm install --global elm-package
  - elm-package install --yes
  - elm-make elm/Main.elm --output site/elm.js
